package apoml

sealed interface ApoExp {
    // TODO
    // data class Var ...
    // data class IntLit ...
    // data class UnaryMin ...
    // data class Mult ...
    // data class Plus ...
    // data class Input...
    // data class LetIn...
}